version: '3.3'

networks: 
  database_network:
    driver: bridge

volumes:
  local_database_data: {}
  local_database_data_backups: {}

services:
  database:
    build:
      context: .
      dockerfile: ./compose/database/Dockerfile
    restart: always
    container_name: database
    volumes:
      - local_database_data:/var/lib/postgresql/data
      - local_database_data_backups:/backups
    networks:
      - database_network
    ports: 
      - 8001:5432

  backend:
    container_name: backend
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    volumes:
      - ./frontend:/app